image: zantan/general:alpine
pipelines:
  branches:
    #Runs only on commit to the master branch.
    master:
      - step:
          script:
            - cd $BITBUCKET_CLONE_DIR/src
            #...do the build *before* doing a test.
            - gradle doBuild
            - gradle doTest