[package]

name = "leek2"
version = "0.0.1"
authors = [ "Me <me@me.me>" ]

#We're still defining basic functionality;
#uncomment this once we're past making a
#logger.
#[dependencies]
#The OpenGL wrapper.
#glium = "*"

[[bin]]

name = "leek2"